### PR TITLE
Merge Pike related change into master

### PR DESCRIPTION
**Pull request by jsuchome**
And bump the version so we can use the old version for older products.

### CODE REVIEW

**Comment by jsuchome** [comment]
Bump to new version might not be needed if the Pike driver patch is backwards compatible...

**Comment by cmurphy** [comment]
Did you test this? I thought there were other breaking changes in Pike but I don't recall what they were.

**Review by cmurphy — APPROVED** [review]
Oh I guess I wrote this

**Comment by jsuchome** [comment]
@cmurphy do you think it works in Newton as well? That way I would not need to play with the version

**Comment by cmurphy** [comment]
It probably works in Newton, but a version increment is still good so we can release it on PyPI

**Review by rhafer — APPROVED** [review]

**Comment by cmurphy** [comment]
Released on PyPI https://pypi.org/project/keystone-json-assignment/0.0.3/

**Pull request merged**
